import os
from pathlib import Path


class VMatGenerator:
    def __init__(self, config):
        self.config = config

    def generate(self, fbx_path, texture_data, bin_data, work_dirs):
        print(f"Генерация .vmat материала для: {fbx_path.name}")

        material_name = fbx_path.stem
        output_dir = Path(work_dirs.get('model_output', work_dirs['output'])).resolve()
        material_data = self.create_material_structure(material_name, texture_data, bin_data, output_dir)

        vmat_path = output_dir / f"{material_name}.vmat"

        with open(vmat_path, 'w', encoding='utf-8') as f:
            f.write(self.format_vmat_content(material_data))

        print(f".vmat файл создан: {vmat_path.name}")
        return vmat_path

    def create_material_structure(self, material_name, texture_data, bin_data, output_dir):
        material = {
            'Material': {
                'shader': 'generic.vfx',
                'properties': {
                    'g_bFullyOpaque': True,
                    'g_nShadowCast': True
                },
                'texture_params': {},
                'vector_params': {},
                'float_params': {}
            }
        }
        if texture_data.get('normal'):
            material['Material']['texture_params']['g_tNormal'] = {
                'resource': self.make_relative_texture_path(texture_data['normal'], output_dir)
            }

        if texture_data.get('specular'):
            material['Material']['texture_params']['g_tSpecular'] = {
                'resource': self.make_relative_texture_path(texture_data['specular'], output_dir)
            }

        if texture_data.get('albedo'):
            material['Material']['texture_params']['g_tColor'] = {
                'resource': self.make_relative_texture_path(texture_data['albedo'], output_dir)
            }
        if texture_data.get('detail_final'):
            self.add_detail_layer(material, texture_data, bin_data, output_dir)

        if 'material_params' in bin_data:
            self.apply_bin_parameters(material, bin_data['material_params'])

        return material

    def add_detail_layer(self, material, texture_data, bin_data, output_dir):

        detail_scale = bin_data.get('material_params', {}).get('detail_scale', 6.0)
        normal_strength = bin_data.get('material_params', {}).get('normal_strength', 1.0)

        material['Material']['texture_params']['g_tDetail'] = {
            'resource': self.make_relative_texture_path(texture_data['detail_final'], output_dir)
        }

        if texture_data.get('detail_normal'):
            material['Material']['texture_params']['g_tDetailNormal'] = {
                'resource': self.make_relative_texture_path(texture_data['detail_normal'], output_dir)
            }

        material['Material']['float_params']['g_flDetailScale'] = detail_scale
        material['Material']['float_params']['g_flDetailNormalStrength'] = normal_strength
        material['Material']['properties']['g_bDetail'] = True
        material['Material']['vector_params']['g_vDetailTint'] = [1.0, 1.0, 1.0]
        material['Material']['float_params']['g_flDetailBlendFactor'] = 1.0

    def apply_bin_parameters(self, material, bin_params):
        specular_level = bin_params.get('specular_level', 0.5)
        material['Material']['float_params']['g_flSpecularStrength'] = specular_level

        if 'g_flDetailNormalStrength' not in material['Material']['float_params']:
            normal_strength = bin_params.get('normal_strength', 1.0)
            material['Material']['float_params']['g_flNormalStrength'] = normal_strength

    def make_relative_texture_path(self, texture_path, base_dir):
        texture_path = Path(texture_path).resolve()
        base_dir = Path(base_dir).resolve()
        try:
            rel_path = texture_path.relative_to(base_dir)
        except ValueError:
            rel_path = Path(os.path.relpath(texture_path, base_dir))
        normalized = str(rel_path).replace('\\', '/')
        return f"./{normalized}"

    def format_vmat_content(self, material_data):
        content = ('// Generated by FBX to VMDL Converter\n'
                   '// Material for S&Box\n\n'
                   'Layer0\n{{\n'
                   '  g_flModelTintAmount "1.000000"\n'
                    '  g_vColorTint "[1.000000 1.000000 1.000000]"\n')

        for tex_name, tex_info in material_data['Material']['texture_params'].items():
            resource_path = tex_info['resource'].replace('\\', '/')
            content += f'  {tex_name} "[{resource_path}]"\n'
        for param_name, param_value in material_data['Material']['float_params'].items():
            content += f'  {param_name} "{param_value:.6f}"\n'

        for param_name, param_value in material_data['Material']['vector_params'].items():
            if isinstance(param_value, list):
                vec_str = " ".join([f"{v:.6f}" for v in param_value])
                content += f'  {param_name} "[{vec_str}]"\n'
        content += "}\n"

        for prop_name, prop_value in material_data['Material']['properties'].items():
            content += f'{prop_name} {"1" if prop_value else "0"}\n'

        return content